version: '3'

services:

  prometheus:
    # prometheus http://localhost:9090/targets
    # micrometer
    #   json http://localhost:9000/q/metrics/json
    #   prometheus http://localhost:9000/q/metrics/prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./configuration/prometheus.yml:/etc/prometheus/prometheus.yml:Z
    networks:
      - my-network

  jaeger:
    # jaeger ui http://localhost:16686
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 5775:5775
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
      - 4317:4317
    networks:
      - my-network

networks:
  my-network:
    name: movie-network
  backend:
    name: jaeger-network